// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: C2GMsg.proto

package com.github.wp17.lina.proto.msg;

public final class C2GMsgProto {
  private C2GMsgProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014C2GMsg.proto\032\roptions.protoB-\n\036com.git" +
      "hub.wp17.lina.proto.msgB\013C2GMsgProtob\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.github.wp17.lina.proto.msg.Options.getDescriptor(),
        }, assigner);
    com.github.wp17.lina.proto.msg.Options.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
