// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: G2RMsg.proto

package com.github.wp17.lina.proto.msg;

public final class G2RProto {
  private G2RProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface G2RUpdateReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:G2RUpdateReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 roleId = 1;</code>
     */
    long getRoleId();

    /**
     * <code>int64 score = 2;</code>
     */
    long getScore();
  }
  /**
   * Protobuf type {@code G2RUpdateReq}
   */
  public  static final class G2RUpdateReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:G2RUpdateReq)
      G2RUpdateReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use G2RUpdateReq.newBuilder() to construct.
    private G2RUpdateReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private G2RUpdateReq() {
      roleId_ = 0L;
      score_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private G2RUpdateReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              roleId_ = input.readInt64();
              break;
            }
            case 16: {

              score_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.wp17.lina.proto.msg.G2RProto.internal_static_G2RUpdateReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.wp17.lina.proto.msg.G2RProto.internal_static_G2RUpdateReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.wp17.lina.proto.msg.G2RProto.G2RUpdateReq.class, com.github.wp17.lina.proto.msg.G2RProto.G2RUpdateReq.Builder.class);
    }

    public static final int ROLEID_FIELD_NUMBER = 1;
    private long roleId_;
    /**
     * <code>int64 roleId = 1;</code>
     */
    public long getRoleId() {
      return roleId_;
    }

    public static final int SCORE_FIELD_NUMBER = 2;
    private long score_;
    /**
     * <code>int64 score = 2;</code>
     */
    public long getScore() {
      return score_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (roleId_ != 0L) {
        output.writeInt64(1, roleId_);
      }
      if (score_ != 0L) {
        output.writeInt64(2, score_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (roleId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, roleId_);
      }
      if (score_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, score_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.wp17.lina.proto.msg.G2RProto.G2RUpdateReq)) {
        return super.equals(obj);
      }
      com.github.wp17.lina.proto.msg.G2RProto.G2RUpdateReq other = (com.github.wp17.lina.proto.msg.G2RProto.G2RUpdateReq) obj;

      boolean result = true;
      result = result && (getRoleId()
          == other.getRoleId());
      result = result && (getScore()
          == other.getScore());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ROLEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRoleId());
      hash = (37 * hash) + SCORE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getScore());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.wp17.lina.proto.msg.G2RProto.G2RUpdateReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.wp17.lina.proto.msg.G2RProto.G2RUpdateReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.wp17.lina.proto.msg.G2RProto.G2RUpdateReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.wp17.lina.proto.msg.G2RProto.G2RUpdateReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.wp17.lina.proto.msg.G2RProto.G2RUpdateReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.wp17.lina.proto.msg.G2RProto.G2RUpdateReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.wp17.lina.proto.msg.G2RProto.G2RUpdateReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.wp17.lina.proto.msg.G2RProto.G2RUpdateReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.wp17.lina.proto.msg.G2RProto.G2RUpdateReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.wp17.lina.proto.msg.G2RProto.G2RUpdateReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.wp17.lina.proto.msg.G2RProto.G2RUpdateReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.wp17.lina.proto.msg.G2RProto.G2RUpdateReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.wp17.lina.proto.msg.G2RProto.G2RUpdateReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code G2RUpdateReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:G2RUpdateReq)
        com.github.wp17.lina.proto.msg.G2RProto.G2RUpdateReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.wp17.lina.proto.msg.G2RProto.internal_static_G2RUpdateReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.wp17.lina.proto.msg.G2RProto.internal_static_G2RUpdateReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.wp17.lina.proto.msg.G2RProto.G2RUpdateReq.class, com.github.wp17.lina.proto.msg.G2RProto.G2RUpdateReq.Builder.class);
      }

      // Construct using com.github.wp17.lina.proto.msg.G2RProto.G2RUpdateReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        roleId_ = 0L;

        score_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.wp17.lina.proto.msg.G2RProto.internal_static_G2RUpdateReq_descriptor;
      }

      public com.github.wp17.lina.proto.msg.G2RProto.G2RUpdateReq getDefaultInstanceForType() {
        return com.github.wp17.lina.proto.msg.G2RProto.G2RUpdateReq.getDefaultInstance();
      }

      public com.github.wp17.lina.proto.msg.G2RProto.G2RUpdateReq build() {
        com.github.wp17.lina.proto.msg.G2RProto.G2RUpdateReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.wp17.lina.proto.msg.G2RProto.G2RUpdateReq buildPartial() {
        com.github.wp17.lina.proto.msg.G2RProto.G2RUpdateReq result = new com.github.wp17.lina.proto.msg.G2RProto.G2RUpdateReq(this);
        result.roleId_ = roleId_;
        result.score_ = score_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.wp17.lina.proto.msg.G2RProto.G2RUpdateReq) {
          return mergeFrom((com.github.wp17.lina.proto.msg.G2RProto.G2RUpdateReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.wp17.lina.proto.msg.G2RProto.G2RUpdateReq other) {
        if (other == com.github.wp17.lina.proto.msg.G2RProto.G2RUpdateReq.getDefaultInstance()) return this;
        if (other.getRoleId() != 0L) {
          setRoleId(other.getRoleId());
        }
        if (other.getScore() != 0L) {
          setScore(other.getScore());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.wp17.lina.proto.msg.G2RProto.G2RUpdateReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.wp17.lina.proto.msg.G2RProto.G2RUpdateReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long roleId_ ;
      /**
       * <code>int64 roleId = 1;</code>
       */
      public long getRoleId() {
        return roleId_;
      }
      /**
       * <code>int64 roleId = 1;</code>
       */
      public Builder setRoleId(long value) {
        
        roleId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 roleId = 1;</code>
       */
      public Builder clearRoleId() {
        
        roleId_ = 0L;
        onChanged();
        return this;
      }

      private long score_ ;
      /**
       * <code>int64 score = 2;</code>
       */
      public long getScore() {
        return score_;
      }
      /**
       * <code>int64 score = 2;</code>
       */
      public Builder setScore(long value) {
        
        score_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 score = 2;</code>
       */
      public Builder clearScore() {
        
        score_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:G2RUpdateReq)
    }

    // @@protoc_insertion_point(class_scope:G2RUpdateReq)
    private static final com.github.wp17.lina.proto.msg.G2RProto.G2RUpdateReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.wp17.lina.proto.msg.G2RProto.G2RUpdateReq();
    }

    public static com.github.wp17.lina.proto.msg.G2RProto.G2RUpdateReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<G2RUpdateReq>
        PARSER = new com.google.protobuf.AbstractParser<G2RUpdateReq>() {
      public G2RUpdateReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new G2RUpdateReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<G2RUpdateReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<G2RUpdateReq> getParserForType() {
      return PARSER;
    }

    public com.github.wp17.lina.proto.msg.G2RProto.G2RUpdateReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_G2RUpdateReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_G2RUpdateReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014G2RMsg.proto\032\roptions.proto\"4\n\014G2RUpda" +
      "teReq\022\016\n\006roleId\030\001 \001(\003\022\r\n\005score\030\002 \001(\003:\005\230\202" +
      "\031\321\017B*\n\036com.github.wp17.lina.proto.msgB\010G" +
      "2RProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.github.wp17.lina.proto.msg.Options.getDescriptor(),
        }, assigner);
    internal_static_G2RUpdateReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_G2RUpdateReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_G2RUpdateReq_descriptor,
        new java.lang.String[] { "RoleId", "Score", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.github.wp17.lina.proto.msg.Options.messageId);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.github.wp17.lina.proto.msg.Options.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
