// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service.proto

package com.github.wp17.lina.proto.rpc.service;

public final class ServiceProto {
  private ServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rService.proto\032\ntest.proto2#\n\007Greeter\022\030" +
      "\n\010SayHello\022\005.Test\032\005.TestB8\n&com.github.w" +
      "p17.lina.proto.rpc.serviceB\014ServiceProto" +
      "P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.github.wp17.lina.proto.msg.TestProto.getDescriptor(),
        }, assigner);
    com.github.wp17.lina.proto.msg.TestProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
